service: appsync-crud
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    name: ${self:service}-${self:provider.stage}
    authenticationType: API_KEY
    schema: schema.graphql

appSync:
  name: ${self:custom.appSync.name}
  authenticationType: ${self:custom.appSync.authenticationType}

  mappingTemplates:
    - dataSource: ItemsTable
      type: Query
      field: getItem
      request: vtl/getItemRequest.vtl
      response: vtl/getItemResponse.vtl

  dataSources:
    - type: AMAZON_DYNAMODB
      name: ItemsTable
      config:
        tableName: { Ref: ItemsTable }

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemsTable-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST 